# On Screen Controller Settings

# Alpha of the background box, 0 (opaque) to 255 (fully transparent).
boxalpha=100
seekbarstyle=diamond

# Colors
background_color=#2E3441
title_color=#C8D0E0
timecode_color=#C8D0E0
time_pos_outline_color=#2E3441
time_pos_color=#C8D0E0
buttons_color=#C8D0E0
top_buttons_color=#C8D0E0
held_element_color=#C8D0E0

# Size of the tooltip outline when using bottombar or topbar layouts.
tooltipborder=3

# Show total time instead of time remaining.
timetotal=yes

# Show OSC only when the mouse hovers it.
deadzonesize=1

# title= ${clock}  󰦺  ${media-title}
title= ${clock}  󰦺  ${filename}

