#!/bin/sh
# Brightness block using "light"

case $BLOCK_BUTTON in
	1) light -A 2 ;;			# left click
	3) light -U 2 ;;			# right click
	2) sleep 2 && xset dpms force off ;;	# middle click
	4) light -A 5 ;;			# scroll up
	5) light -U 5 ;;			# scroll down
esac

urgent=2

getBrightness=$(light -G)
curBrightness=${getBrightness%.*}

[ "$curBrightness" -le "$urgent" ] && exit 33

echo "$curBrightness%"
echo "$curBrightness%"

exit 0
