#!/bin/bash
# Copyright (C) 2018 Yusuf Aktepe <yusuf@yusufaktepe.com>

[ ! "$(mpc status 2>/dev/null)" ] && [ ! "$(playerctl status 2>/dev/null)" ] && exit

ICON_PLAY=""
ICON_PAUSE=""
ICON_STOP=""
CUR_ICON=""

if pidof mpd >/dev/null; then
	STATUS=$(mpc status 2>/dev/null); STATUS=${STATUS##*\[}; STATUS=${STATUS%%\]*}
	ARTIST=$(mpc current --format=%artist% 2>/dev/null)
	TITLE=$(mpc current --format=%title% 2>/dev/null)
else
	STATUS=$(playerctl status 2>/dev/null)
	ARTIST=$(playerctl metadata artist 2>/dev/null)
	TITLE=$(playerctl metadata title 2>/dev/null)
fi

trunc() {
	if [ "${#1}" -gt 22 ]; then
		V="${1:0:21}…"
		V=${V/% ?…/…}
		V=${V/% \(?…/…}
		V=${V/% \[?…/…}
		V=${V/% -?…/…}
		V=${V/% …/…}
		V=${V/%..…/…}
		V=${V/%.…/…}
		V=${V/%:…/…}
		V=${V/%-…/…}
		V=${V/%,…/…}
		V=${V/%;…/…}
		V=${V/% …/…}
	else
		return 1
	fi
}

output() {
	trunc "$ARTIST" && ARTIST="$V"
	trunc "$TITLE" && TITLE="$V"

	if [ "${STATUS,,}" = "paused" ]; then
		CUR_ICON="$ICON_PAUSE"
	elif [ "${STATUS,,}" = "playing" ]; then
		CUR_ICON="$ICON_PLAY"
	else
		CUR_ICON="$ICON_STOP"
	fi

	[ "$TITLE" != "" ] && [ "$ARTIST" != "" ] && echo "$CUR_ICON $ARTIST - $TITLE"
}

case $BLOCK_BUTTON in
	1) smc t ;;
	2) smc p ;;
	3) smc n ;;
	4) smc vol up ;;
	5) smc vol down ;;
esac

output
