#!/bin/bash
# shellcheck disable=2034

PROMPT=''

kb_bind[1]='F3'
kb_bind[2]='F4'
kb_bind[3]='F5'
kb_bind[4]='F6'
kb_bind[5]='3'
kb_bind[6]='4'
kb_bind[7]='5'
kb_bind[8]='6'
kb_bind[9]='t'
kb_bind[10]='y'
kb_bind[11]='c'
kb_bind[12]='d'

kb_act[1]="bro-open $BROWSER"
kb_act[2]="bro-open opera --start-maximized"
kb_act[3]="bro-open firefox"
kb_act[4]="bro-open google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode"
kb_act[5]="bro-open $BROWSER --incognito"
kb_act[6]="bro-open opera -private --start-maximized"
kb_act[7]="bro-open firefox --private-window"
kb_act[8]="bro-open google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode --incognito"
kb_act[9]="bro-open tor-browser --allow-remote"
kb_act[10]="bro-open mpv"
kb_act[11]="bro-open mpv -c"
kb_act[12]="bro-open dmenuhandler"

kb_msg[1]='vivaldi'
kb_msg[2]='opera'
kb_msg[3]='firefox'
kb_msg[4]='chrome'
kb_msg[5]='vivaldi[P]'
kb_msg[6]='opera[P]'
kb_msg[7]='firefox[P]'
kb_msg[8]='chrome[P]'
kb_msg[9]='tor-browser'
kb_msg[10]='mpv'
kb_msg[11]='mpv[C]'
kb_msg[12]='dmenuhandler'

