#!/bin/bash
# shellcheck disable=2034

PROMPT=''

kb_bind[1]='F3'
kb_bind[2]='F4'
kb_bind[3]='F5'
kb_bind[4]='F6'
kb_bind[5]='F7'
kb_bind[6]='3'
kb_bind[7]='4'
kb_bind[8]='5'
kb_bind[9]='6'
kb_bind[10]='7'
kb_bind[11]='t'
kb_bind[12]='y'
kb_bind[13]='c'
kb_bind[14]='d'

kb_act[1]="bro-open vivaldi-stable --enable-features=WebUIDarkMode --force-dark-mode --start-maximized"
kb_act[2]="bro-open opera --start-maximized"
kb_act[3]="GTK_THEME=Adwaita-dark bro-open firefox"
kb_act[4]="bro-open google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode --test-type"
kb_act[5]="bro-open brave --test-type"
kb_act[6]="bro-open vivaldi-stable --enable-features=WebUIDarkMode --force-dark-mode --start-maximized --incognito"
kb_act[7]="bro-open opera -private --start-maximized"
kb_act[8]="GTK_THEME=Adwaita-dark bro-open firefox --private-window"
kb_act[9]="bro-open google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode --incognito --test-type"
kb_act[10]="bro-open brave --incognito --test-type"
kb_act[11]="bro-open tor-browser --allow-remote"
kb_act[12]="bro-open mpv"
kb_act[13]="bro-open mpv -c"
kb_act[14]="bro-open dmenuhandler"

# kb_msg[1]='vivaldi'
# kb_msg[2]='opera'
# kb_msg[3]='firefox'
# kb_msg[4]='chrome'
# kb_msg[5]='brave'
# kb_msg[6]='vivaldi[P]'
# kb_msg[7]='opera[P]'
# kb_msg[8]='firefox[P]'
# kb_msg[9]='chrome[P]'
# kb_msg[10]='brave[P]'
# kb_msg[11]='tor-browser'
# kb_msg[12]='mpv'
# kb_msg[13]='mpv[C]'
# kb_msg[14]='dmenuhandler'

