#!/bin/bash
# shellcheck disable=2034

PROMPT=''

kb_bind[1]='F3'
kb_bind[2]='F4'
kb_bind[3]='F5'
kb_bind[4]='3'
kb_bind[5]='4'
kb_bind[6]='5'
kb_bind[7]='t'
kb_bind[8]='y'
kb_bind[9]='c'
kb_bind[10]='d'

kb_act[1]="bro-open vivaldi-stable --start-maximized"
kb_act[2]="bro-open firefox"
kb_act[3]="bro-open google-chrome-stable"
kb_act[4]="bro-open vivaldi-stable --start-maximized --incognito"
kb_act[5]="bro-open firefox --private"
kb_act[6]="bro-open google-chrome-stable --incognito"
kb_act[7]="bro-open tor-browser --allow-remote"
kb_act[8]="bro-open mpv"
kb_act[9]="bro-open mpv -c"
kb_act[10]="bro-open dmenuhandler"

# kb_msg[1]='vivaldi'
# kb_msg[2]='opera'
# kb_msg[3]='firefox'
# kb_msg[4]='chrome'
# kb_msg[5]='brave'
# kb_msg[6]='vivaldi[P]'
# kb_msg[7]='opera[P]'
# kb_msg[8]='firefox[P]'
# kb_msg[9]='chrome[P]'
# kb_msg[10]='brave[P]'
# kb_msg[11]='tor-browser'
# kb_msg[12]='mpv'
# kb_msg[13]='mpv[C]'
# kb_msg[14]='dmenuhandler'

