#!/bin/bash
# shellcheck disable=2034

PROMPT=''

kb_bind[1]='q'
kb_bind[2]='g'
kb_bind[3]='minus'
kb_bind[4]='asterisk'

kb_act[1]="autotype mail"
kb_act[2]="autotype mail2"
kb_act[3]="autotype banner"
kb_act[4]="autotype banner2"

kb_msg[1]='mail'
kb_msg[2]='mail2'
kb_msg[3]='banner'
kb_msg[4]='banner2'

