#!/bin/bash
# shellcheck disable=2034

PROMPT=''

kb_bind[1]='1'
kb_bind[2]='2'
kb_bind[3]='3'
kb_bind[4]='4'
kb_bind[5]='5'
kb_bind[6]='p'

kb_act[1]="gpaste -p 1"
kb_act[2]="gpaste -p 2"
kb_act[3]="gpaste -p 3"
kb_act[4]="gpaste -p 4"
kb_act[5]="gpaste -p 5"
kb_act[6]="gpaste --selpaste"

kb_msg[1]='paste @1'
kb_msg[2]='paste @2'
kb_msg[3]='paste @3'
kb_msg[4]='paste @4'
kb_msg[5]='paste @5'
kb_msg[6]='paste selection'

