#!/bin/sh
# Notify me if my battery is below 35%.
# !!! Use systemd timer instead.
# */5 * * * * $HOME/.local/bin/cron/cronbat

BAT="BAT1"

[ "$(cat /sys/class/power_supply/${BAT}/status)" = "Unknown" ] && exit

[ "$(cat /sys/class/power_supply/${BAT}/capacity)" -lt 35 ] &&

notify-send-cron -a system -u critical "Battery critically low."
