#!/bin/sh
# Executed by startx

uXmodmap="$XDG_CONFIG_HOME/X11/Xmodmap"
uXresources="$XDG_CONFIG_HOME/X11/Xresources"

[ -f "$uXmodmap" ] && xmodmap "$uXmodmap"
[ -f "$uXresources" ] && xrdb -merge "$uXresources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Autostart
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
(setbg; sleep 1; picom -b) &
dunst &
nm-applet &
redshift &
remaps &
numlockx &
greenclip daemon &
unclutter &

exec "${1:-i3}"
