#!/bin/sh

Unread=$(curl -su "$GMAIL":"$GMAILAP" https://mail.google.com/mail/feed/atom | grep -oP '<fullcount>\K[[:alnum:]]+')

[ -z "$Unread" ] && exit

Icon=''
Color=#bb81A1C1
ColorUnread=#bbBF616A

if [ "$Unread" -gt 0 ]; then
	printf '%s\n' "%{F$ColorUnread}$Icon%{F-} $Unread"
else
	printf '%s\n' "%{F$Color}$Icon%{F-} $Unread"
fi

