#!/bin/bash
# Copyright (C) 2020 Yusuf Aktepe <yusuf@yusufaktepe.com>

ICON_PLAY=""
ICON_PAUSE=""
ICON_STOP=""
CUR_ICON=""

output() {
	[ ! "$(mpc status 2>/dev/null)" ] && [ ! "$(playerctl status 2>/dev/null)" ] && echo "" && exit

	if pgrep -x mpd > /dev/null; then
		STATUS=$(mpc status 2>/dev/null | awk -v RS='[' -v FS=']' 'END {print $1}')
		ARTIST=$(mpc current --format=%artist% 2>/dev/null)
		TITLE=$(mpc current --format=%title% 2>/dev/null)
	else
		STATUS=$(playerctl status 2>/dev/null)
		ARTIST=$(playerctl metadata artist 2>/dev/null)
		TITLE=$(playerctl metadata title 2>/dev/null)
	fi

	[ "${#ARTIST}" -gt 20 ] && AO="${ARTIST:0:20}.." && \
		AO=${AO/% ../..} && AO=${AO/%.../..} && \
		AO=${AO/% ?../..} && AO=${AO/%-../..} && AO=${AO/% \(?../..} || AO=$ARTIST

	[ "${#TITLE}" -gt 20 ] && TO="${TITLE:0:20}.." && \
		TO=${TO/% ../..} && TO=${TO/%.../..} && \
		TO=${TO/% ?../..} && TO=${TO/%-../..} && TO=${TO/% \(?../..} || TO=$TITLE

	if [ "${STATUS,,}" = "paused" ]; then
		CUR_ICON="$ICON_PAUSE"
	elif [ "${STATUS,,}" = "playing" ]; then
		CUR_ICON="$ICON_PLAY"
	else
		CUR_ICON="$ICON_STOP"
	fi

	[ "$TITLE" != "" ] && [ "$ARTIST" != "" ] && echo "$CUR_ICON $AO - $TO"
}

trap "output" USR1

while :; do
	output
	sleep 5 &
	wait
done

