#!/bin/sh

kbc="MousePrimary,MouseSecondary,Super_L,Control_L,Control_R,Alt_L,\
ISO_Level3_Shift,Shift_L,Shift_R,space,Escape,XF86Launch2,XF86Launch9"

rn() {
	timeout 10 rofi -kb-cancel "$kbc" -location 3 -width 15 \
		-e "<span color='#ebdbb2'>$1</span>" -markup
}

case $1 in
	mem) rn "$(printf " Memory hogs:\n--------------------";\
		ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	cpu) rn "$(printf " CPU hogs:\n--------------------";\
		ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac
